version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: orbital_db
    environment:
      POSTGRES_USER: orbital_admin
      POSTGRES_PASSWORD: orbital_password
      POSTGRES_DB: orbital_mission_db
    ports:
      - "5432:5432"
    volumes:
      - orbital_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  orbital_pgdata:
