import React, { useState } from 'react';
import { useAthreix } from '../../context/AthreixContext.jsx';

/**
 * ReportGenerator — One-click intelligence report export.
 * 
 * Generates downloadable reports from the latest analysis results:
 * - JSON (full machine-readable data)
 * - GeoJSON (change mask polygons)
 * - CSV (metrics table)
 * - Markdown (human-readable report)
 */
export default function ReportGenerator() {
  const { state } = useAthreix();
  const { activeMission, analysisResults, location, selectedYear } = state;
  const [exporting, setExporting] = useState(false);

  const mission = activeMission;
  const results = mission?.results || analysisResults;

  if (!results) return null;

  const downloadFile = (content, filename, mimeType) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportJSON = () => {
    setExporting(true);
    const report = {
      _meta: {
        generator: 'ORBITAL Intelligence Platform',
        version: '2.0',
        exported_at: new Date().toISOString(),
        location: { lat: location.lat, lon: location.lon, name: location.name },
        year: selectedYear,
      },
      analysis: results,
    };
    downloadFile(JSON.stringify(report, null, 2), `orbital_report_${Date.now()}.json`, 'application/json');
    setExporting(false);
  };

  const exportGeoJSON = () => {
    const geojson = results.geojson_mask;
    if (!geojson) return;
    downloadFile(JSON.stringify(geojson, null, 2), `orbital_change_mask_${Date.now()}.geojson`, 'application/geo+json');
  };

  const exportCSV = () => {
    const metrics = results.quantitative_metrics || {};
    const rows = [['Metric', 'Value']];
    for (const [key, val] of Object.entries(metrics)) {
      rows.push([key, String(val)]);
    }
    const csv = rows.map(r => r.join(',')).join('\n');
    downloadFile(csv, `orbital_metrics_${Date.now()}.csv`, 'text/csv');
  };

  const exportMarkdown = () => {
    const text = results.text || 'No analysis text available.';
    const meta = results.agent_metadata || {};
    const md = [
      `# ORBITAL Intelligence Report`,
      ``,
      `**Generated:** ${new Date().toISOString()}`,
      `**Location:** ${location.name || 'Unknown'} (${location.lat.toFixed(4)}°N, ${location.lon.toFixed(4)}°E)`,
      `**Year:** ${selectedYear}`,
      `**Data Quality:** ${meta.data_quality || 'unknown'}`,
      `**Specialists:** ${(meta.specialists_invoked || []).join(', ')}`,
      ``,
      `---`,
      ``,
      text,
      ``,
      `---`,
      ``,
      `*Generated by AETHREIX ORBITAL v2.0*`,
    ].join('\n');
    downloadFile(md, `orbital_report_${Date.now()}.md`, 'text/markdown');
  };

  return (
    <div className="report-generator glass-panel-subtle">
      <div className="report-header">
        <span className="report-title">Export Report</span>
      </div>
      <div className="report-buttons">
        <button className="report-btn" onClick={exportJSON} disabled={exporting}>
          <span className="report-btn-icon">{ }</span>
          <span>JSON</span>
        </button>
        {results.geojson_mask && (
          <button className="report-btn" onClick={exportGeoJSON}>
            <span className="report-btn-icon">🗺️</span>
            <span>GeoJSON</span>
          </button>
        )}
        {results.quantitative_metrics && (
          <button className="report-btn" onClick={exportCSV}>
            <span className="report-btn-icon">📋</span>
            <span>CSV</span>
          </button>
        )}
        <button className="report-btn" onClick={exportMarkdown}>
          <span className="report-btn-icon">📄</span>
          <span>Report</span>
        </button>
      </div>
    </div>
  );
}
